node {
    def projectId = 'carshowroom-241614'
    def appName = 'carshowroom'
    def namespace = 'default'
    def imageVersion = "v0.0.${env.BUILD_NUMBER}"
    def buildName = "gcr.io/${projectId}/${appName}"
    def buildTag = "${imageVersion}-BUILD-SNAPSHOT"
    def imageName = "${buildName}:${buildTag}"

    stage('Build') {
    	git 'https://github.com/inkrot/carshowroom-server.git'
    	sh 'gradle build -g build/gradle-5.4.1'
    }

    stage('Test') {
    	sh 'gradle test -g build/gradle-5.4.1'
    }

    stage('Containerize') {
        withCredentials([file(credentialsId: 'key-sa', variable: 'GC_KEY')]) {
            sh("gcloud auth activate-service-account --key-file=${GC_KEY}")
            sh("gcloud container clusters get-credentials carshowroom-cluster --zone us-central1-b")
            sh("docker build -t ${imageName} .")
            sh("docker push ${imageName}")
        }
    }

    stage('Deploy') {
    	sh """
            export CURRENT_BUILD_IMAGE_NAME=${imageName}
            envsubst < deployment/carshowroom.yaml | kubectl apply -f -
        """
    }
}